//! Sequencer step.

use serde::{Deserialize, Serialize};

use crate::params::{Pitch, Velocity};

/// Sequencer step.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Step {
    /// Flag if step is enabled for playing.
    enabled: bool,

    /// Event for this step.
    event: Option<StepEvent>,
}

impl Step {
    /// Returns a new step with a specific event.
    pub fn new(event: Option<StepEvent>) -> Self {
        Self {
            event,
            ..Default::default()
        }
    }

    /// Enables the step.
    pub fn enable(&mut self) {
        self.enabled = true;
    }

    /// Disables the step.
    pub fn disable(&mut self) {
        self.enabled = false;
    }

    /// Returns if the step is enabled.
    pub fn enabled(&self) -> bool {
        self.enabled
    }

    /// Sets a new event.
    pub fn set_event(&mut self, event: Option<StepEvent>) {
        self.event = event;
    }

    /// Returns a shared reference to the event.
    pub fn event(&self) -> &Option<StepEvent> {
        &self.event
    }

    /// Returns a mutable reference to the event.
    pub fn event_mut(&mut self) -> &mut Option<StepEvent> {
        &mut self.event
    }
}

/// Events generated by a step.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum StepEvent {
    /// Start a note.
    NoteOn {
        /// Pitch of the note.
        pitch: Pitch,

        /// Velocity of the note.
        vel: Velocity,
    },

    /// Stop a note.
    NoteOff {
        /// Pitch of the note.
        pitch: Pitch,
    },
}
